#!/usr/bin/env bash
# Prints bad luck on 4th iteration and good luck at 8th iteration
k=1
while ((k<=10)); do
	if ((k==4)); then
		echo bad luck
	elif ((k==8)); then
		echo good luck
	else
		echo Best School
	fi
	k=$((k+1))
done
